bitfinexcom/bitfinex-api-py

.travis.yml, bfxapi/models/Order.py, bfxapi/models/order.py, bfxapi/websockets/OrderManager.py, pylint.rc, requirements.txt
This pull request is pretty small and just fixes a few issues I picked up on when manuell testing the python honey framework client.
=> Little fixes

README.md, bfxapi/models/Subscription.py, bfxapi/models/subscription.py, bfxapi/rest/BfxRest.py, bfxapi/websockets/BfxWebsocket.py, bfxapi/websockets/SubscriptionManager.py
- fixes typo
- fixes payload sent to unsibscribe subscription
=> subscription: fix unsubscrbe

.travis.yml, README.md, bfxapi/tests/test_ws_orders.py, bfxapi/utils/testing_tools.py, bfxapi/websockets/BfxWebsocket.py, bfxapi/websockets/GenericWebsocket.py, bfxapi/websockets/OrderManager.py, bfxapi/websockets/SubscriptionManager.py, requirements.txt
This PR:
- Improves order callback system
- Adds run-unit test script ot travis
- Adds a bunch of new unit tests (mostly for callbacks)
- Add ability to manually close websocket using close()
- Update readme with changes
- Adds modules to requirements
=> Improve callbacks

.travis.yml, bfxapi/Client.py, bfxapi/client.py, bfxapi/rest/BfxRest.py, bfxapi/websockets/BfxWebsocket.py, requirements.txt
Changes the defauly websocket and rest endpoint from `api-pub.bitfinex.com/v2` to `api-pub.bitfinex.com/v2`
=> change default api endpoint to api-pub

bfxapi/websockets/SubscriptionManager.py
New Bitfinex API limits means that each connection can only support max 30 channels at once. This pull request adds a limit to the library that enforces this rule (max 25 connections).
=> Subscriptions: limit channels to 25 per instance

bfxapi/Client.py, bfxapi/__init__.py, bfxapi/client.py, bfxapi/models/Subscription.py, bfxapi/models/subscription.py, bfxapi/tests/helpers.py, bfxapi/tests/test_ws_capacity.py, bfxapi/tests/test_ws_orders.py, bfxapi/utils/testing_tools.py, bfxapi/websockets/BfxWebsocket.py, bfxapi/websockets/GenericWebsocket.py, bfxapi/websockets/OrderManager.py, bfxapi/websockets/SubscriptionManager.py
This pull request creates a manage system that creates new websocket connections whenever the total `available channel capacity` nears to 1 connection. If api credentials are passed then the library will select one (and only one) connection to be used for all authenticated requests.
=> Multiplex ws connection

.github/ISSUE_TEMPLATE, .github/PULL_REQUEST_TEMPLATE, CHANGELOG, bfxapi/__init__.py, bfxapi/version.py
This pull request adds a changelog and version tracking in the main.py file. Also Issue/PR templates have been added to the .github dir.
=> Add templates

bfxapi/websockets/generic_websocket.py
Fix resub for authenticated sockets
- [ X] Fix resub for authenticated sockets
=> Fix resub for authenticated sockets

CHANGELOG, bfxapi/models/order.py, bfxapi/rest/bfx_rest.py, bfxapi/websockets/generic_websocket.py, bfxapi/websockets/order_manager.py, docs/rest_v2.md, docs/ws_v2.md, setup.py
This pull request add the ability to specify `aff_code` (affiliate code) when submitting a new order via both rest and websocket.
None
None
=> Add affiliate code

CHANGELOG, README.md, bfxapi/client.py, bfxapi/examples/ws/connect_auth.py, bfxapi/websockets/bfx_websocket.py, docs/ws_v2.md, setup.py
This pull request adds the ability to specify channel filters in the client constructor. These filters will be passed on via the auth event and will tell the server to only send specific updates that match the given filter.
- None
- None
=> Add channel filter

bfxapi/examples/rest/get_authenticated_data.py, bfxapi/rest/bfx_rest.py
- corrent function from_raw_order not found error
- correct function name typos: rest.get_active_positions -> rest.get_active_position
=> couple of code modifications

CHANGELOG, bfxapi/models/subscription.py, bfxapi/rest/bfx_rest.py, bfxapi/websockets/bfx_websocket.py, bfxapi/websockets/generic_websocket.py, bfxapi/websockets/order_manager.py, setup.py
Issue: https://github.com/bitfinexcom/bitfinex-api-py/issues/42
This pull request adds a mutex and locks it when sending websocket messages in order to prevent the `Fatal error on SSL transport` error.
None
None
=> Fix ssl write error

bfxapi/models/deposit_address.py, bfxapi/models/notification.py, bfxapi/models/order.py, bfxapi/models/position.py, bfxapi/models/subscription.py, bfxapi/models/transfer.py, bfxapi/models/withdraw.py, bfxapi/tests/test_ws_capacity.py, bfxapi/tests/test_ws_orderbook.py, bfxapi/tests/test_ws_orders.py, bfxapi/tests/test_ws_subscriptions.py, bfxapi/utils/auth.py, bfxapi/utils/custom_logger.py, bfxapi/websockets/bfx_websocket.py, bfxapi/websockets/generic_websocket.py, bfxapi/websockets/order_manager.py, bfxapi/websockets/subscription_manager.py
Fixed typos/docstrings and some comments
No breaking changes
No new features
Merely went through and fixed typos/docstrings and some comments
=> Fix docstring, comment typos

bfxapi/examples/rest/get_authenticated_data.py
Current script not showing the correct request parameters for funding. Trade data was included, changed it to show funding data.
...
=> Update Funding script info

CHANGELOG, bfxapi/rest/bfx_rest.py, setup.py
- Implemented additional endpoints (rest)
- Updated setup.py requirements
https://docs.bitfinex.com/reference#rest-public-pulse-hist
https://docs.bitfinex.com/reference#rest-public-pulse-profile
https://docs.bitfinex.com/reference#rest-auth-pulse-hist
https://docs.bitfinex.com/reference#rest-auth-pulse-add
https://docs.bitfinex.com/reference#rest-auth-pulse-del
https://docs.bitfinex.com/reference#rest-auth-order-cancel-multi
https://docs.bitfinex.com/reference#rest-public-calc-foreign-exchange-rate
https://docs.bitfinex.com/reference#rest-public-calc-market-average-price
https://docs.bitfinex.com/reference#rest-auth-deposit-invoice
https://docs.bitfinex.com/reference#rest-auth-keep-funding
- [ None]
- [ PULSE endpoints ]
- [ None ]
- [ ❌ ] Version bumped
- [ ✔️ ] Change-log updated
=> Implemented additional endpoints (rest) + updated setup.py requirements

requirements.txt, setup.py
=> Python 3.9.2 requires websockets 8

CHANGELOG, bfxapi/models/wallet.py, bfxapi/rest/bfx_rest.py, bfxapi/version.py, bfxapi/websockets/wallet_manager.py
Adding `available_balance` to the Wallet.
Available_balance is available in the Wallet.
=> Adding balance_available to the wallet

CHANGELOG, bfxapi/examples/rest/get_authenticated_data.py, bfxapi/models/__init__.py, bfxapi/models/margin_info.py, bfxapi/models/margin_info_base.py, bfxapi/rest/bfx_rest.py, bfxapi/version.py
Implemented Margin Info endpoint and claim position
- []
=> Added Margin Info endpoint & claim position

CHANGELOG, bfxapi/version.py, bfxapi/websockets/generic_websocket.py, setup.py
This PR allows initializing WS client with
```
bfx = Client(
logLevel='DEBUG',
max_retries=0
)
```
to ensure it will retry to connect forever
- []
=> if max_retries == 0 continue forever

CHANGELOG, bfxapi/examples/ws/full_orderbook.py, bfxapi/version.py, setup.py
Added example implementation of https://docs.bitfinex.com/reference#ws-public-books described algorithm to create and keep a book instance updated
=> added full_orderbook.py example

CHANGELOG, bfxapi/examples/rest/create_order.py, bfxapi/examples/ws/send_order.py, bfxapi/version.py, setup.py
Added examples of MARKET orders with price=None
=> Added example of MARKET order with price=None

CHANGELOG, bfxapi/rest/bfx_rest.py, bfxapi/version.py, setup.py
adjusted get_order_history() rest endpoint
=> adjusted get_order_history() rest endpoint

CHANGELOG, bfxapi/version.py, requirements.txt, setup.py
=> updated version of websockets

CHANGELOG, bfxapi/examples/rest/get_authenticated_data.py, bfxapi/rest/bfx_rest.py, bfxapi/version.py, bfxapi/websockets/generic_websocket.py, setup.py
Adjusted get_trades() to allow symbol to be None and get trades for all symbols
=> adjusted get_trades() rest

CHANGELOG, bfxapi/examples/rest/get_authenticated_data.py, bfxapi/rest/bfx_rest.py, bfxapi/version.py, bfxapi/websockets/generic_websocket.py, setup.py
To merge after https://github.com/bitfinexcom/bitfinex-api-py/pull/183
Handle exception of asyncio.get_event_loop() | Related to v1.2.8
=> Handle exception of asyncio.get_event_loop() | Related to v1.2.8

CHANGELOG, bfxapi/examples/rest/merchant.py, bfxapi/rest/bfx_rest.py, bfxapi/version.py, setup.py
Added merchants rest endpoints. Updated CHANGELOG.
=> Merchants endpoints

CHANGELOG, bfxapi/rest/bfx_rest.py, bfxapi/version.py, bfxapi/websockets/subscription_manager.py
There are many PRs never merged due to missing changes to the changelog, version and/or other minor adjustments required.
This PR includes all of them. I am very grateful to the contributors.
1) Avoid p_sub not initialized issue
Credits to @nkasimova (https://github.com/bitfinexcom/bitfinex-api-py/pull/170)
2) Added submit cancel all funding offers endpoint
Credits to @charlychiu (https://github.com/bitfinexcom/bitfinex-api-py/pull/169)
3) Added get all exchange pairs endpoint
Credits to @uggel (https://github.com/bitfinexcom/bitfinex-api-py/pull/79)
None
=> Combined all old unmerged PRs

setup.py
Updated version of setup.py
https://github.com/bitfinexcom/bitfinex-api-py/pull/187
=> updated version (for PR #187)

CHANGELOG, bfxapi/examples/rest/get_liquidations.py, bfxapi/rest/bfx_rest.py, bfxapi/version.py, setup.py
Implemented Liquidations endpoint (REST)
=> implemented liquidations endpoint (rest)

CHANGELOG, bfxapi/models/ledger.py, bfxapi/version.py, setup.py
=> ledger missing id fix

CHANGELOG, bfxapi/models/withdraw.py, bfxapi/version.py, setup.py
=> Fix withdraw fees
