bitfinexcom/bitfinex-api-py

bfxapi/__init__.py, bfxapi/models/Order.py, bfxapi/models/Subscription.py, bfxapi/models/order.py, bfxapi/models/order_book.py, bfxapi/models/subscription.py, bfxapi/rest/BfxRest.py, bfxapi/tests/helpers.py, bfxapi/tests/test_decimal.py, bfxapi/tests/test_ws_orderbook.py, bfxapi/tests/test_ws_orders.py, bfxapi/tests/test_ws_subscriptions.py, bfxapi/utils/Decimal.py, bfxapi/websockets/BfxWebsocket.py, bfxapi/websockets/GenericWebsocket.py, bfxapi/websockets/SubscriptionManager.py, pylint.rc, requirements.txt
Floating point arithmetic meant that we didnt have enough precision to accurately store prices and amounts. This was causing for the BTC pairs to fail checksums etc.
** EDIT **
This pull request fixes that by using the raw string values in order to generate the checksum which is reccomended. Also, optionally you can pass `parse_float=bfxapi.Decimal` in order to force the api to use a data type with much higher precision.
This pull request also adds a new direcotry which contains unit tests for order, subscriptions, orderbook, orders and Decimal object.
=> Convert prices/amounts to Decimals rather than floats

CHANGELOG, README.md, bfxapi/examples/rest/get_authenticated_data.py, bfxapi/examples/rest/get_public_data.py, bfxapi/examples/ws/subscribe_derivative_status.py, bfxapi/models/subscription.py, bfxapi/rest/__init__.py, bfxapi/rest/bfx_rest.py, bfxapi/utils/__init__.py, bfxapi/version.py, bfxapi/websockets/__init__.py, bfxapi/websockets/bfx_websocket.py, bfxapi/websockets/subscription_manager.py, pylint.rc, setup.py
With the release of the bitfinex derivatives engine there are some new additions such as support for new pairs long style pairs i.e DUSK:BTC, DUSK:USD, tBTCF0:USTF0 and also 3 new endpoints:
https://docs.bitfinex.com/v2/reference#status
https://docs.bitfinex.com/v2/reference#ws-public-status
https://docs.bitfinex.com/v2/reference#rest-auth-deriv-pos-collateral-set
None
- New ws event `status_update`
- New rest function `get_derivative_status`
- New rest function `get_derivative_statuses`
- New rest function `set_derivative_collateral`
- New channel support `status`
None
=> Support derivatives

CHANGELOG, bfxapi/client.py, bfxapi/tests/helpers.py, bfxapi/websockets/generic_websocket.py
The websocket multiplexer update broke the interface that the HF data server used. This PR fixes that so the HF strategy can communicate with the HF data server
- [] You can no longer override `loop` in the constructor. But you can now override `create_event_emitter` which adds more flexibility.
None
=> Fix for data server

bfxapi/rest/bfx_rest.py
Python 3.8 sometimes throws linting errors when 'Is not None' is used
- ~~Version bumped~~
- ~~Change-log updated~~
=> bfx_rest: change 'is not None' to '!= None'

bfxapi/models/withdraw.py
fees used as amount because of missing parameter in text variable.
...
=> Fix object formatting

CHANGELOG, bfxapi/utils/custom_logger.py, bfxapi/version.py, bfxapi/websockets/generic_websocket.py, setup.py
An issue (https://github.com/bitfinexcom/bitfinex-api-py/issues/65) was raised which reports that the CPU utilization of the websocket client exceeds 100%. The problem is, that in order to keep the event emitter thread alive, the code uses a `while True` loop with `sleep(0)`.
In order to solve this issue, the event emitter thread has been set to a `daemon` thread which means it will keep alive (until the process exits) without needing an aggressive `while True` loop.
- None
- None
=> generic_websocket: set event_emmiter thread to daemon

CHANGELOG, bfxapi/models/__init__.py, bfxapi/models/ledger.py, bfxapi/rest/bfx_rest.py, bfxapi/version.py
Ledgers were missing from the REST api: https://docs.bitfinex.com/reference#rest-auth-ledgers
- None
- async def get_ledgers(self, symbol, start, end, limit=25, category=None):
"""
Get all ledgers on account associated with API_KEY - Requires authentication.
See category filters here: https://docs.bitfinex.com/reference#rest-auth-ledgers
@return Array <models.Ledger>
"""
- None
=> adds get_ledgers

bfxapi/websockets/order_manager.py
The order manager class containes provisions to automatically keep a list of open, pending and closed orders. In the current state of the class, only the list for open orders is maintained correctly. 
- None
- (New) closed orders will now be added to the 'closed_orders' dict
- Once pending orders are confirmed, they will be removed from the 'pending_orders' dict
- New features could also be argued to be a fix.
=> FIX: order manager did not manage 'closed_orders' and 'pending_orders'

CHANGELOG, bfxapi/version.py, bfxapi/websockets/generic_websocket.py, requirements.txt
bitfinex-api.py was using an old version of pyee, this did not allow the correct execution on Python 3.7 and 3.8.
I have updated pyee to last version (8.0.1) and changed the deprecated EventEmitter() with AsyncIOEventEmitter().
Now it works with all Python 3.X versions.
"On emit, the event emitter will automatically schedule the coroutine using asyncio.ensure_future and the configured event loop (defaults to asyncio.get_event_loop())." (https://pyee.readthedocs.io/en/latest/#pyee.AsyncIOEventEmitter)
- None
- None
- Compatibility with Python 3.7 and 3.8
- [✔️ ] Version bumped
- [ ✔️] Change-log updated
=> Python 3.X compatibility

requirements.txt, setup.py
Based in this comment thread: https://github.com/bitfinexcom/bitfinex-api-py/pull/99#discussion_r567021718
Which implemented changes in this PR: https://github.com/bitfinexcom/bitfinex-api-py/pull/88/files
Versions in setup.py shouldn't be pinned.
https://packaging.python.org/discussions/install-requires-vs-requirements/?highlight=install_requires
Removed also dev dependencies, as setup.py should only keep the ones used for production. For dev and testing you use the ones in requirements.txt.
To understand `~=` check here: https://pip.pypa.io/en/latest/user_guide/#understanding-your-error-message
>~=3.1: version 3.1 or later, but not version 4.0 or later. ~=3.1.2: version 3.1.2 or later, but not version 3.2.0 or later.
So, in sum `setup.py` should request the minimum compatible version. …
=> Use ranges in setup.py versions

CHANGELOG, bfxapi/rest/bfx_rest.py, bfxapi/version.py
I have re-implemented get_seed_candles() to make it consistent with the actual behaviour of the endpoint. It is no more necessary to send multiple requests and sort the result
- No, this patch does not generate breaking changes
- get_seed_candles() has been fixed in a backwards compatibility manner
- [✔️] Version bumped
- [✔️] Change-log updated
=> get_seed_candles() has been fixed in a backwards compatibility manner

bfxapi/rest/bfx_rest.py
get_public_candles (line 99) : limit arg was set as string while below it is defined as int
get_public_trades (line 121) : limit arg was set as string while below it is defined as int
updated definitions: wrong value format given for arguments in definition.
=> fix: wrong value format in definition

CHANGELOG, bfxapi/version.py, bfxapi/websockets/bfx_websocket.py, bfxapi/websockets/order_manager.py
Please see https://github.com/bitfinexcom/bitfinex-api-py/issues/123
If an invalid order is submitted, it is now removed from pending_orders.
```
[BfxOrderManager] [INFO] Order cid=1617705257122 (tBTCUSD -25 @ 4) dispatched
[BfxWebsocket] [DEBUG] [0,"n",[1617705257166,"on-req",null,null,[null,null,1617705257122,"tBTCUSD",null,null,-25,null,"EXCHANGE LIMIT",null,null,null,0,null,null,null,4,null,0,0,null,null,null,0,0,null,null,null,null,null,null,{}],null,"ERROR","Invalid order: not enough exchange balance for -25 BTCUSD at 4"]]
[BfxOrderManager] [INFO] Deleted Order CID 1617705257122 from pending orders
[BfxWebsocket] [ERROR] Notification ERROR: Invalid order: not enough exchange balance for -25 BTCUSD at 4
```
If an EXCHANGE_FILL_OR_KILL order is unfilled and cancelled it is now removed …
=> Invalid orders should be removed from pending_orders

CHANGELOG, bfxapi/rest/bfx_rest.py, bfxapi/tests/test_rest_get_public_trades.py, setup.py
#When using get_public_trades with sort=1, the orders are not sorted properly whenever there are multiple trades occurring at the same time. I've sent this issue to your support team a while ago but it would be nice to have a fix on the interface level as well.
Please see full issue thread here -> https://github.com/bitfinexcom/bitfinex-api-py/issues/124
=> get_public_trades() orders should be sorted by [timestamp, id]

CHANGELOG, bfxapi/version.py, bfxapi/websockets/bfx_websocket.py
bfx_websockets.py ERRORS dictionary now contains a message for error number 10305
=> Added missing error to ERRORS

bfxapi/models/order.py
Flag "close=True" in order didn't work (when size of open position was less than min order size) due to typo in close flag value. 
Changed value to 512 in accordance with https://docs.bitfinex.com/docs/flag-values.
=> Fixed a bug in 'close position' flag

bfxapi/rest/bfx_rest.py, bfxapi/websockets/order_manager.py
It was impossible to set up 'time in force' during order update because of irrelevant key name in payload( 'time_in_force' instead of 'tif'). Changed key name to 'tif' in update_order func (like implemented in submit_order func).
=> Fixed bug in setting 'time in force' in order update

CHANGELOG, bfxapi/version.py, bfxapi/websockets/generic_websocket.py, setup.py
A user reported that calling self.bfx.ws.run() from an async function freezes the execution of the program due to the while loop (https://github.com/bitfinexcom/bitfinex-api-py/pull/182/files#diff-5a4859241d03c91d234e0858da6b2ec849b490b086a33e1201a9ab861067e191R90), but the latter is necessary when you call bfx.ws.run() [in this other way.](https://github.com/bitfinexcom/bitfinex-api-py/blob/master/bfxapi/examples/ws/update_order.py#L41)
=> Bugfix - It is now possible to call bfx.ws.run() from an already running event loop

CHANGELOG, bfxapi/utils/decorators.py, bfxapi/version.py, bfxapi/websockets/bfx_websocket.py, setup.py
This fixes the following error
```
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x10202c5e0>
transport: <_SelectorSocketTransport fd=18 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
File "/Users/mkml/.pyenv/versions/3.9.5/lib/python3.9/asyncio/sslproto.py", line 672, in _process_write_backlog
data, offset = self._write_backlog[0]
IndexError: deque index out of range
socket.send() raised exception.
Error in data transfer
RuntimeError: cannot schedule new futures after shutdown
```
=> Fixed socket.send() issue (IndexError: deque index out of range)

CHANGELOG, bfxapi/__init__.py, bfxapi/client.py, bfxapi/constants.py, bfxapi/examples/rest/create_funding.py, bfxapi/examples/rest/create_order.py, bfxapi/examples/rest/get_authenticated_data.py, bfxapi/examples/rest/get_public_data.py, bfxapi/examples/rest/get_seed_trades.py, bfxapi/examples/rest/merchant.py, bfxapi/examples/rest/transfer_wallet.py, bfxapi/examples/ws/cancel_order.py, bfxapi/examples/ws/connect.py, bfxapi/examples/ws/connect_auth.py, bfxapi/examples/ws/full_orderbook.py, bfxapi/examples/ws/multiple_instances.py, bfxapi/examples/ws/resubscribe_orderbook.py, bfxapi/examples/ws/send_order.py, bfxapi/examples/ws/start_stop_connection.py, bfxapi/examples/ws/subscribe_derivative_status.py, bfxapi/examples/ws/subscribe_orderbook.py, bfxapi/examples/ws/subscribe_tickers.py, bfxapi/examples/ws/subscribe_trades_candles.py, bfxapi/examples/ws/update_order.py, bfxapi/examples/ws/wallet_balance.py, bfxapi/version.py, bfxapi/websockets/bfx_websocket.py, setup.py
Updated code to change private host for auth-based requests and updated examples
=> Use private host for auth-based requests
